### ISSUE TITLE
deal with accidental em-dash

### ISSUE THREAD

**Issue by trentm** [trentm/node-dashdash#12]
Presumably would need an option to turn this off/on. Major ver bump if default is to check for em-dashes.

The problem is that cut 'n paste in certain contexts (e.g. IM clients) will change "--foo" into "—foo" and the option processing will be a surprise. Would be nice to deal with this somehow.

An idea: Add a new "emdash" option to the dashdash parser with values: "error", "treat as --", "ignore"  (pick better names for these).

**Comment by theartoflogic** [comment]
Another option is to add additional parser options that define the `longPrefix` and `shortPrefix`. It could default to  `--` and `-`, respectively. That way you could override the `longPrefix` as `[ '--', '—' ]` to support both a double-dash and emdash. It could also be overriden to support any other prefix someone may want.

Example:

```js
var parser = dashdash.createParser({ longPrefix: [ '--', '—' ] });
```

Ps. It might also be useful to define a `marker` option that defaults to `--`. This would allow you to override it as `[ '--', '—' ]` as well, since that would likely be replaced with an emdash as well in those cases.

e.g. supports `--test1 arg1 -- --test2` as well as `--test1 arg1 — --test2`

**Comment by trentm** [comment]
I like that design. However until there are other example use cases for other prefixes this all feels a little like featuritis

--Trent

**Comment by trentm** [comment]
I'm calling YAGNI.
